name: Robot Control CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch: # Habilita la ejecución manual desde la pestaña de Actions.

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - uses: actions/checkout@v4

      # 2. Configurar Java con Caché
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Evita descargar dependencias en cada ejecución

      # 3. Ejecutar los tests
      - name: Build and Test
        run: mvn -B clean test # Logs más limpios

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/